### ISSUE TITLE
County and City Aggregation

### ISSUE THREAD

**Issue by JacobWren** [jacobkap/nibrsbook#10]
In regards to both the UCR and NIBRS data sets, do you have any qualms about aggregating to the county level?

Also, is it possible to aggregate to the city level?

Thanks

**Comment by jacobkap** [comment]
Using the standard imputation method for county-level data has huge issues as I note here: https://ucrbook.com/county-level-ucr-data.html. It's possible to aggregate to the city level if you have a way of determining which city each agency is in.

**Comment by JacobWren** [comment]
@jacobkap ah yes, great chapter. In terms of city aggregation, the issue I am facing is that in the state I am considering a large number of people live outside of city limits (i.e., in the unincorporated part of the county). Thus, if the Sheriff’s Office or State Police were involved, I have no way of distinguishing whether the crime happened inside or outside of city limits.
