### ISSUE TITLE
List of all police agencies

### ISSUE THREAD

**Issue by jrisi256** [jacobkap/nibrsbook#12]
Howdy Dr. Kaplan,

Thanks for making this book and making the data more readily available on ICPSR.

My apologies if I missed this somewhere, but I was curious if there is a full list of all police agencies in the USA somewhere. For example, how did you build your crosswalk file?

The goal is to understand the nationwide response rate for NIBRS reporting. I see in your book you use the percentage which reported to UCR, but I would like all police agencies and not just those reporting to UCR.

**Comment by jacobkap** [comment]
Hi,

This file has a list of all agencies in the US: https://www.icpsr.umich.edu/web/NACJD/studies/35158. I built my crosswalk file based on this and previous versions of it (also available on the ICPSR website).
