### ISSUE TITLE
Tracking motor vehicle theft/damage/recovery

### ISSUE THREAD

**Issue by moxboxwa** [jacobkap/nibrsbook#13]
Hi Jacob,

First off, thx so much for putting this resource together.  There seems to be quite a bit of user guidance for LEAs who submit data to  NIBRS, but almost nothing for data analysts on the other end.  So this book is really helpful, and GitHub to crowd source the corrections and expansions is on point.

I have both a question for you, and an offer.

Big picture: I'd like to know what fraction of motor vehicle thefts are recovered (with/without damage) and what fraction are cleared by arrest/exception.

__QUESTION:__

My question has to do with how to track the status of stolen motor vehicles.  These are identified by PROP_DESC_ID = 3 in the property segment and OFFENSE_TYPE_ID = 21 in the offense segment.

Some vehicles are recovered, with or without damage.  All of this information appears to be carried in one field of the property segment:   PROP_LOSS_ID (data element 14).  The codes in that field are:

----

1 = None 
2 = Burned (includes damage caused in fighting the fire) 
3 = Counterfeited/Forged 
4 = Destroyed/Damaged/Vandalized 
5 = Recovered (to impound property that was previously stolen) 
6 = Seized (to impound property that was not previously stolen) 
7 = Stolen/Etc. (includes bribed, defrauded, embezzled, extorted, ransomed, robbed, etc.) 
8 = Unknown 

----

Because only one code can be selected, a single record can not be used to report both the theft of the car (code 7), the recovery of the car (code 5) and its condition on recovery (code 4 if damaged).

I believe this means that multiple records will exist in the property segment for a single stolen vehicle if it is recovered.  Or, another way of saying this, every stolen vehicle that is recovered will have at least 2 records in the property segment:  one for the theft, the other for the recovery.   These related records can be identified by the combination of INCIDENT_ID / PROP_DESC_ID (03) / OFFENSE_TYPE_ID (21).

By extension, to report damage to the recovered stolen vehicle a third record would be required, with code 4 for the PROP_LOSS_ID.

Do you know if this is correct?

__OFFER__

My offer is, if you are able to help me get this analysis done correctly (or just refer me to someone who might be able to verify what I've suggested above), I'd be happy to contribute an example (with an R script if useful) to your book to guide others.

Thanks!  Martina

**Comment by jacobkap** [comment]
Good question. Yes that is correct. Agencies can report multiple records for the same incident so you could see, for example, one row about the stolen vehicle and a second value for the recovered vehicle. For example, unique_incident_id "al0010200 2w2jpu7u8nt4" (which I generated by combining the ori column and the incident_number column) has two rows: the first shows that the type of property loss is "stolen/etc. (includes bribed, defrauded, embezzled, extorted, ransomed, robbed, etc.)" and the second shows that the type of property loss is "recovered". In both cases the property_description is "automobiles", the incident date is 2022-05-26, the date_recovered for the second row is 2022-05-31, and the value of the property is 1500. If the car was damaged there would be a third row for that incident.
