### ISSUE TITLE
subpopulation victimization rates at the jurisdiction level - what denominator?

### ISSUE THREAD

**Issue by sparker6** [jacobkap/nibrsbook#15]
Hi Jacob - apologies if I missed this in your book when I looked, but wanted to ask: what is the most accurate way to calculate victimization rates by age / race / sex or other subpopulation at the agency level? I imagine the best population denominator is the FBI's agency population but that will not line up to a single county population figure in all cases. 

Would it be sensible to calculate the rate of, say, agg assaults for victims over 65 to match the agency's county to the Census, obtain the proportion of the county population that is over 65, and apply that the the FBI's agency population? If an agency matches to two counties, maybe just take the average? 

Thank you! -susan

**Comment by jacobkap** [comment]
Hi Susan,

That's right, an agency will not line up to the county population in most cases. So you really shouldn't be using an agency's crime data with a county's population. Dealing with county-level data has a long history of criminologists - including myself - warning people against and other people - often other criminologists - doing so anyways. https://ucrbook.com/county-level-ucr-data.html
