### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by JacobWren** [jacobkap/nibrsbook#4]
Hello,

In the NIBRS Master file, for the Administrative segment, I have come across duplicate entries (I am solely looking at the state of Oregon). I have the years 2010-2019, but duplicates are only appearing in 2017 and 2018. To put this in context, only 16 of the entries are duplicated. Nevertheless, why is this?

Please see the df at https://colab.research.google.com/drive/1EQvwX-kisjzvTE4MhGEHCu8qDoHyA_RI?usp=sharing to concretely see the problem I have encountered. 

Thanks.

**Comment by jacobkap** [comment]
Hi, great question. I've seen that too and while the unique ID is the same, the number of other segments (e.g. number of victim segments differs even though unique ID is the same) is different. This should never occur and even if the agency updates an incident it should not lead to a duplicate row. So my belief is that it's just a mistake on either the reporting agency or the FBI's end where they incorrectly reuse the same ID for an incident.

**Comment by JacobWren** [comment]
Thank you, Dr. Kaplan, but your response seems a better fit to issue #2 that I raised. In this case, the number of other segments is identical. I am not sure whether to simply remove the duplicates or treat them as distinct cases, but it seems more likely that this is just an error in which case a few entries were accidentally copied twice.

**Comment by jacobkap** [comment]
Oh. In that case I'd recommend just dropping the duplicates. I believe that these are just erroneous copies.
