### ISSUE TITLE
Batch Header Segment

### ISSUE THREAD

**Issue by JacobWren** [jacobkap/nibrsbook#6]
Hello Dr. Kaplan,

Would you consider providing the Batch Header Segment? I know the segment is time-invariant across incidents, but not across years. While your website does link the ORI code to the agency, the BH segments provide other information. 

Thanks

**Comment by jacobkap** [comment]
I haven't included batch headers because for most of the years of data the FBI Master Files only have the ORI ID for the agency in the batch header segment, not any other columns.
