### ISSUE TITLE
ORI to Agency

### ISSUE THREAD

**Issue by JacobWren** [jacobkap/nibrsbook#9]
Hello Dr. Kaplan,

I hope I am not bugging you at this point... but I figure you enjoy this stuff anyway.

While I could scrap your site, would you consider making the data found here https://jacobdkaplan.com/crosswalk.html downloadable? 

Thanks

**Comment by jacobkap** [comment]
Good idea. Data is attached.
[crosswalk.csv](https://github.com/jacobkap/nibrsbook/files/7799778/crosswalk.csv)
